language: node_js

node_js:
  - 13

cache:
  directories:
    - node_modules
    - bin

addons:
  apt:
    update: true

script:
  - make

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true
