dist: xenial

cache:
  directories:
    - node_modules

addons:
  apt:
    update: true
  snaps:
    - hugo

script:
  - make

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
